In [1]:
Import Numpy with the alias np

In [ ]:
import numpy as np

In [ ]:
Create a simple Numpy array

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [ ]:
Create a Numpy array that is auto populated with 10 elements

In [8]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Slice the array print everything up to element 5

In [10]:
array[:5]

array([0, 1, 2, 3, 4])

In [ ]:
Slice the array to print everything from 5 to the end

In [11]:
array[5:]

array([5, 6, 7, 8, 9])

In [ ]:
Slice the array to print elements from 4 to 7

In [12]:
array[4:7]

array([4, 5, 6])

In [ ]:
Slice the array to print every second element (skip by 2)

In [13]:
array[::2]

array([0, 2, 4, 6, 8])

In [ ]:
Slice the array to print every second element (starting from 1)

In [14]:
array[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
Slice the array to print every second element in the array (starting from one and ending at 5 and skipping by 2)

In [15]:
array[1:5:2]

array([1, 3])

In [ ]:
Slice the array to print every third element

In [16]:
array[::3]

array([0, 3, 6, 9])

In [ ]:
Slice the array to print all elements starting from 1

In [17]:
array[1::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Create a Numpy multidimensional array

In [4]:
mdarray = np.array([[1,2,3,4], [5,6,7,8]])
mdarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
mdarray2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
mdarray2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.random.seed(1)
j = np.random.randint(10, size=(3,4))
j

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [21]:
print(j[0, :])

[5 8 9 5]


In [22]:
print(j[1, 1:3])

[0 1]


In [23]:
print(j[2, 0:3])

[6 9 2]


In [26]:
print(j[0, 1:])

[8 9 5]


In [27]:
print(j[0:2, 1:])

[[8 9 5]
 [0 1 7]]


In [28]:
print(j[0:3, :1])

[[5]
 [0]
 [6]]


In [29]:
p = np.arange(9)

In [30]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
x = p.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Concatenation (combining) of Arrays in Numpy

In [33]:
q = np.array([10,11,12,13])
r = np.array([14,15,16,17])
np.concatenate([q,r])

array([10, 11, 12, 13, 14, 15, 16, 17])

In [34]:
np.random.seed(1)
x = np.random.randint(10, size=(4,4))
print(x)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]


In [35]:
x[1:3, 0:3]

array([[0, 0, 1],
       [6, 9, 2]])

In [36]:
a = np.arange(10)
a[:3]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
print(a[3:6])

[3 4 5]


In [38]:
x = np.arange(10)
i = np.array([2,1,8,4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [39]:
x = np.arange(10)
i = np.array([6,4])
x[i] = 6
print(x)

[0 1 2 3 6 5 6 7 8 9]


In [40]:
dict_1 = {
    'Dallas': 'Cowboys',
    'Green Bay': 'Packers',
    'New England': 'Patriots',
    'Philadelphia': 'Eagles',
    'Seattle': 'Seahawks'
}

In [41]:
print(dict_1[0])

KeyError: 0

In [42]:
print(dict_1['Dallas'])

Cowboys


In [43]:
dict_1["New Orleans"] = "Saints"

In [44]:
print(dict_1)

{'Dallas': 'Cowboys', 'Green Bay': 'Packers', 'New England': 'Patriots', 'Philadelphia': 'Eagles', 'Seattle': 'Seahawks', 'New Orleans': 'Saints'}


In [ ]:
del dict_1['Philidelphia']

In [45]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
x[3:7]

array([3, 4, 5, 6])

In [47]:
x[:4]

array([0, 1, 2, 3])

In [48]:
np.random.seed(1)
x=np.random.randint(10, size=(4,4))
print(x)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]


In [49]:
print(x[:4, :2])

[[5 8]
 [0 0]
 [6 9]
 [5 2]]


In [50]:
print(x[1:3, 0:3])

[[0 0 1]
 [6 9 2]]


In [51]:
d = np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
print(d[:3, :3])

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
