In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import sys
!{sys.executable} -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 15.3 MB 2.4 MB/s eta 0:00:01    |█████████▊                      | 4.6 MB 679 kB/s eta 0:00:16


In [3]:
import numpy as np

In [5]:
a = np.zeros(3)

In [6]:
a


array([0., 0., 0.])

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
z = np.linspace(1, 20, 5)
z

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [11]:
y = np.linspace(2, 20, 1)
y

array([2.])

In [12]:
y = np.linspace(1, 20, 20)
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [13]:
a = [1, 2, 3, 4, 5]
b = np.array([a])
b

array([[1, 2, 3, 4, 5]])

In [14]:
c = np.array([1,2,3,4,5,6,7])
c

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
type(c)

numpy.ndarray

In [16]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((5,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [18]:
new = np.array([1,2,3,4], [5,6,7,8])
new

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [19]:
g = np.array([1,2,3], [4,5,6])
g

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [20]:
g = np.array([[1,2,3], [4,5,6]])
g

array([[1, 2, 3],
       [4, 5, 6]])